
[build]
  command = "pip install -r requirements.txt" # Ensures dependencies are ready
  publish = "public"                          # Point this to a folder with a blank index.html
  functions = "netlify/functions"             # Where your api.py lives

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

